services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: bloodbank
      POSTGRES_PASSWORD: bloodbank123
      POSTGRES_DB: bloodbankdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5001:5001"
      - "5555:5555"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata: